import type { Body } from "./types.js";

// Scale: 1 AU = 100 Three.js units
// Radii: real_km × 0.5 / 6371  (Earth = 0.5 units)
// Sun radius: 10 units (fixed)
// Planets spread at their orbital radii with varied phase angles for natural look

export const SCENE_BODIES: Record<string, Body[]> = {
  "solar-system": [
    {
      id: "sun",
      name: "Sun",
      mass: 1.989e30,
      radius: 10,
      position: [0, 0, 0],
      velocity: [0, 0, 0],
      texture: "sun",
      color: "#FDB813",
      rings: null,
    },
    {
      id: "mercury",
      name: "Mercury",
      mass: 3.301e23,
      radius: 0.191,
      position: [38.7, 0, 0],
      velocity: [0, 0, 0],
      texture: "mercury",
      color: "#b5b5b5",
      rings: null,
    },
    {
      id: "venus",
      name: "Venus",
      mass: 4.867e24,
      radius: 0.475,
      position: [0, 0, 72.3],
      velocity: [0, 0, 0],
      texture: "venus",
      color: "#e8cda0",
      rings: null,
    },
    {
      id: "earth",
      name: "Earth",
      mass: 5.972e24,
      radius: 0.5,
      position: [-100, 0, 0],
      velocity: [0, 0, 0],
      texture: "earth",
      color: "#4fa3e0",
      rings: null,
    },
    {
      id: "mars",
      name: "Mars",
      mass: 6.417e23,
      radius: 0.266,
      position: [0, 0, -152.4],
      velocity: [0, 0, 0],
      texture: "mars",
      color: "#c1440e",
      rings: null,
    },
    {
      id: "jupiter",
      name: "Jupiter",
      mass: 1.898e27,
      radius: 5.483,
      position: [520.3, 0, 0],
      velocity: [0, 0, 0],
      texture: "jupiter",
      color: "#c88b3a",
      rings: null,
    },
    {
      id: "saturn",
      name: "Saturn",
      mass: 5.683e26,
      radius: 4.567,
      position: [0, 0, 953.7],
      velocity: [0, 0, 0],
      texture: "saturn",
      color: "#e8d5a1",
      rings: {
        innerRadius: 6.6,
        outerRadius: 15.0,
        texture: "saturn-rings-color",
      },
    },
    {
      id: "uranus",
      name: "Uranus",
      mass: 8.681e25,
      radius: 1.990,
      position: [-1919, 0, 0],
      velocity: [0, 0, 0],
      texture: "uranus",
      color: "#7de8e8",
      rings: null,
    },
    {
      id: "neptune",
      name: "Neptune",
      mass: 1.024e26,
      radius: 1.932,
      position: [0, 0, -3007],
      velocity: [0, 0, 0],
      texture: "neptune",
      color: "#5b5ddf",
      rings: null,
    },
  ],

  "earth-moon": [
    {
      id: "sun",
      name: "Sun",
      mass: 1.989e30,
      radius: 10,
      position: [-10000, 0, 0],
      velocity: [0, 0, 0],
      texture: "sun",
      color: "#FDB813",
      rings: null,
    },
    {
      id: "earth",
      name: "Earth",
      mass: 5.972e24,
      radius: 0.5,
      position: [0, 0, 0],
      velocity: [0, 0, 0],
      texture: "earth",
      color: "#4fa3e0",
      rings: null,
    },
  ],

  "custom": [],
};
